# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0jcG7UHkoysA01ksFbdGjOfGdYWcNoh
"""

import pandas as pd

"""# Задача №57. 
1. Прочесть с помощью pandas файл california_housing_test.csv, который находится в папке sample_data
2. Посмотреть сколько в нем строк и столбцов
3. Определить какой тип данных имеют столбцы
"""

df = pd.read_csv('sample_data/california_housing_test.csv')

df.shape

df.dtypes